### ISSUE TITLE
Getting this error in development "Accessing PropTypes via the main React package is deprecated"

### ISSUE THREAD

**Issue by avishekjana** [jaredt67/redux-nprogress#8]
I'm getting this error in React 15.5.0 and above. It seems that propTypes is used in a component, which is deprecated as per the latest React release.

```
// In lib/NProgressComponent.js Line no. 85
NProgressComponent.propTypes = {
  nprogress: _react.PropTypes.object
};
```
How to solve this problem?

**Comment by eudaimos** [comment]
This was fixed in #4 but @jaredt67 it doesn't appear that the built version being published to npm has the fix (per above and what I have locally = same as above when updating to `1.0.0`) + I'm still getting the warning

You'll probably have to push a v`1.0.1` patch for npm

**Comment by kyeo76** [comment]
published new version

**Comment by avishekjana** [comment]
@jaredt67 Great! It's working now.

**Comment by eudaimos** [comment]
thanks @jaredt67
